### ISSUE TITLE
It's asking for my device name every time i restart awl

### ISSUE THREAD

**Issue by dillfrescott** [anywherelan/awl#127] opened 2024-06-18 01:56 UTC
On windows. i think the settings aren't saving properly perhaps

**Comment by pymq** [comment] 2024-06-19 06:57
Hi! Starting from recent releases it's necessary to provide device name because it's used in some internal logic. Did you try to fill the name in press save and it won't save? I just tried it and can't reproduce

**Comment by dillfrescott** [comment] 2024-06-19 22:50
Yeah, I clicked save every time and id restart the daemon and it would ask for it again.

**Comment by pymq** [comment] 2024-06-20 06:31
Hmm, do you restart daemon right after saving device name or after some time (10+ minutes)?

Can you try to save device name and then update some other peer info or add new peer (anyone) and delete them?

If that doesn't help, could you find error logs in Server Logs tab in UI?

**Comment by dillfrescott** [comment] 2024-06-23 03:43
Sorry, I think its working now and I'm not sure what had caused the issue previously! I'll close this as I think it was some sort of fluke or error on my end!

**Comment by pymq** [comment] 2024-06-23 09:18
I think you were right, there is an error in updating code, I'm just not totally sure it was the same error you were facing. Nevertheless, thanks for reporting it!

**Comment by dillfrescott** [comment] 2024-06-23 09:19
Oh okay!

**Comment by pymq** [comment] 2024-06-23 09:39
Fix will be in the next release

**Closed** 2024-06-23 09:39 UTC
Labels: bug
